name: CI / CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd web-app
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python ${{ matrix.python-version }}
          pipenv install pytest
          pipenv install
          pipenv run python -m pytest
      - name: Test with pytest
        run: |
          cd web-app
          pipenv run python -m pytest
  push_to_registry:
    needs: [build]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        # if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # if: github.ref == 'refs/heads/main'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # if: github.ref == 'refs/heads/main'
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: doodyshark/se-web-app

      - name: Build and push Docker image
        # if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}